### ISSUE TITLE
rails new

### ISSUE THREAD

**Issue by msm0046** [msm0046/api-sample#1]
## 1. RailsをAPIモードでnewする

**railsコマンド/オプション**

- APIモード
`--api`

- DBをpostgresqlに指定
`-d postgresql`

**実行コマンド**
```
rails new . --skip-yarn --skip-active-storage --skip-action-cable --skip-sprockets --skip-coffee --skip-javascript --skip-turbolinks --no-rc --skip-bundle --api -d postgresql
```

**実行結果**
- 通常とは違い、removeされたファイルも表示されている
```
       exist  
      create  README.md
      create  Rakefile
      create  .ruby-version
      create  config.ru
      create  .gitignore
      create  Gemfile
         run  git init from "."
Reinitialized existing Git repository in /Users/komatsumasumi/CODEBASE/api_sample/.git/
      create  app
      create  app/assets/config/manifest.js
      create  app/assets/stylesheets/application.css
      create  app/channels/application_cable/channel.rb
      create  app/channels/application_cable/connection.rb
      create  app/controllers/application_controller.rb
      create  app/helpers/application_helper.rb
      create  app/javascript/channels/consumer.js
      create  app/javascript/channels/index.js
      create  app/javascript/packs/application.js
      create  app/jobs/application_job.rb
      create  app/mailers/application_mailer.rb
      create  app/models/application_record.rb
      create  app/views/layouts/application.html.erb
      create  app/views/layouts/mailer.html.erb
      create  app/views/layouts/mailer.text.erb
      create  app/assets/images
      create  app/assets/images/.keep
      create  app/controllers/concerns/.keep
      create  app/models/concerns/.keep
      create  bin
      create  bin/rails
      create  bin/rake
      create  bin/setup
      create  bin/yarn
      create  config
      create  config/routes.rb
      create  config/application.rb
      create  config/environment.rb
      create  config/puma.rb
      create  config/spring.rb
      create  config/environments
      create  config/environments/development.rb
      create  config/environments/production.rb
      create  config/environments/test.rb
      create  config/initializers
      create  config/initializers/application_controller_renderer.rb
      create  config/initializers/assets.rb
      create  config/initializers/backtrace_silencers.rb
      create  config/initializers/content_security_policy.rb
      create  config/initializers/cookies_serializer.rb
      create  config/initializers/cors.rb
      create  config/initializers/filter_parameter_logging.rb
      create  config/initializers/inflections.rb
      create  config/initializers/mime_types.rb
      create  config/initializers/new_framework_defaults_6_0.rb
      create  config/initializers/wrap_parameters.rb
      create  config/locales
      create  config/locales/en.yml
      create  config/master.key
      append  .gitignore
      create  config/boot.rb
      create  config/database.yml
      create  db
      create  db/seeds.rb
      create  lib
      create  lib/tasks
      create  lib/tasks/.keep
      create  lib/assets
      create  lib/assets/.keep
      create  log
      create  log/.keep
      create  public
      create  public/404.html
      create  public/422.html
      create  public/500.html
      create  public/apple-touch-icon-precomposed.png
      create  public/apple-touch-icon.png
      create  public/favicon.ico
      create  public/robots.txt
      create  tmp
      create  tmp/.keep
      create  tmp/pids
      create  tmp/pids/.keep
      create  tmp/cache
      create  tmp/cache/assets
      create  vendor
      create  vendor/.keep
      create  test/fixtures
      create  test/fixtures/.keep
      create  test/fixtures/files
      create  test/fixtures/files/.keep
      create  test/controllers
      create  test/controllers/.keep
      create  test/mailers
      create  test/mailers/.keep
      create  test/models
      create  test/models/.keep
      create  test/helpers
      create  test/helpers/.keep
      create  test/integration
      create  test/integration/.keep
      create  test/channels/application_cable/connection_test.rb
      create  test/test_helper.rb
      remove  app/assets
      remove  lib/assets
      remove  tmp/cache/assets
      remove  app/helpers
      remove  test/helpers
      remove  app/views/layouts/application.html.erb
      remove  public/404.html
      remove  public/422.html
      remove  public/500.html
      remove  public/apple-touch-icon-precomposed.png
      remove  public/apple-touch-icon.png
      remove  public/favicon.ico
      remove  app/javascript
      remove  config/initializers/assets.rb
      remove  app/javascript/channels
      remove  app/channels
      remove  test/channels
      remove  config/initializers/cookies_serializer.rb
      remove  config/initializers/content_security_policy.rb
      remove  config/initializers/new_framework_defaults_6_0.rb
      remove  bin/yarn
```

**Comment by msm0046** [comment]
## ディレクトリ構成
![image](https://user-images.githubusercontent.com/60738020/91241336-94b56480-e77f-11ea-9f42-926fd133a893.png)

**Comment by msm0046** [comment]
## 2. サーバーを立ち上げる(エラー)

**実行コマンド**
`rails s`

**実行結果**
```
=> Booting Puma
=> Rails 6.0.3.2 application starting in development 
=> Run `rails server --help` for more startup options
Exiting
Traceback (most recent call last):
        37: from bin/rails:4:in `<main>'
        36: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
        35: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        34: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
        33: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        32: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        31: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        30: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        29: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        28: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
        27: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'
        26: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'
        25: from /Library/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        24: from /Library/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        23: from /Library/Ruby/Gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        22: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `perform'
        21: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `tap'
        20: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        19: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:37:in `start'
        18: from /Library/Ruby/Gems/2.6.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
        17: from /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        16: from /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        15: from /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        14: from /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        13: from /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        12: from /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        11: from /Library/Ruby/Gems/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        10: from config.ru:3:in `block in <main>'
         9: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:53:in `require_relative'
         8: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
         7: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
         6: from /Library/Ruby/Gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
         5: from /Library/Ruby/Gems/2.6.0/gems/zeitwerk-2.4.0/lib/zeitwerk/kernel.rb:34:in `require'
         4: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
         3: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         2: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         1: from /Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Library/Ruby/Gems/2.6.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- /Users/user_name/CODEBASE/api_sample/config/environment (LoadError)
```
